### ISSUE TITLE
Ubuntu 22.04 tilemaker-server no static folder in share

### ISSUE THREAD

**Issue by gunyakov** [systemed/tilemaker#667] opened 2024-02-02 14:01 UTC
When I run simple 
`
tilemaker-server bulgaria-latest.mbtiles
`
in browser I get next error
`Could not open path /: boost::filesystem::canonical: No such file or directory: "/home/goodzon/git/static"`

Static folder must be putted in share folder during `sudo make install` and server must look for static folder in share first, and not trying to get this files from local git clone folder.

**Comment by systemed** [comment] 2024-02-02 16:05
Essentially a duplicate of #666.

**Closed by systemed** 2024-02-02 16:05 UTC
